### ISSUE TITLE
Overfull experience bar

### ISSUE THREAD

**Issue by Wuzzy2** [D00Med/LegendofMinetest#11]
The experience bar (?) at the bottom can become overfull when using the triforce many times. It doesn't seem to ever end.

Tested in version 2.

**Comment by D00Med** [comment]
I have attempted to fix this

**Comment by mckaygerhard** [comment]
this issue was fixed it seems since the merge of the pull #39 so must be closed @D00Med  thanks in advance, i tested and cofirmed fixed

![screenshot_20220128_130820](https://user-images.githubusercontent.com/1571724/151590960-565cdc26-742a-464c-9c33-a15bc567e64e.png)
