### ISSUE TITLE
Artificial hive (xdecor) does not work

### ISSUE THREAD

**Issue by Wuzzy2** [D00Med/LegendofMinetest#13]
I waited for a very long time after placing an artificial hive but it never produces honey.

This bug is inherited from `xdecor`:
https://github.com/minetest-mods/xdecor/issues/75

The game appears to have two hives anyway, I don't see the point. Maybe just removing the `xdecor` hive would be the simplest fix.

**Comment by D00Med** [comment]
Did you have flowers near the hive? I've never had any trouble with it.
I will probably remove the hive from mobs_animal.

**Comment by Wuzzy2** [comment]
OK, thanks.
