### ISSUE TITLE
Many issues with crafting grid

### ISSUE THREAD

**Issue by Wuzzy2** [D00Med/LegendofMinetest#14]
Recipes in the 2×2 crafting grid behave oddly.
Try to craft a torch. You can't just place a coal lump (C) and a stick (S) on top of each other.
Instead, you have to place it like this:

    C_
    _S

The recipe seems to be correct, because in the 3×3 grid, it works as expected.

I also noticed the same behaviour with other 1×2 recipes (like the torch).

There is another issue which allows the player to shift-click items into the 2×2 grid even when it is full. Very weird.
Also, if the player placed an item in the bottom right slot in the crafting table, then closes it and opens the normal player inventory again, crafting becomes impossible

Tested in version 2.

HINT: Based on my experience, I had a very similar issue with my own subgame. I figured out that the game failed to correctly set the inventory size and width after swithing between crafting table and normal inventory. The solution for me was to update the player's inventory size whenever it was required.
As changing the inventory size causes a lot of trouble when you keep items inside it, my subgame will also auto-drop all items which are still left in the crafting grid slots after closing.
There is a LOT of weird behaviour when leaving items in the crafting grid and then switching to the other crafting grid size. See for yourself if you want to use this solution, or maybe come up with something else.

**Comment by D00Med** [comment]
Unfortunately it's a totally different shape to what it appears. I'm just going to get rid of it.
I find it annoying having to use the worktable anyway.

**Comment by Wuzzy2** [comment]
Well, this is of course another way to solve the problem. ;-)
I don't mind getting rid of the work table.
