### ISSUE TITLE
music and sounds

### ISSUE THREAD

**Issue by tobyplowy** [D00Med/LegendofMinetest#2]

**Comment by tobyplowy** [comment]
@D00Med what music and sound effects do we need

**Comment by D00Med** [comment]
Music as in the absence of music?

**Comment by D00Med** [comment]
Oh ok. I plan to add effects for the tools/weapons and the mobs first

**Comment by D00Med** [comment]
speaking of which, I've been making new mobs, like zols and moldorm

**Comment by tobyplowy** [comment]
I found someone whos interested in helping with music and sound effects

**Comment by SamLabbato** [comment]
hey what's up
I'm Sam

**Comment by D00Med** [comment]
Hello Sam. And thanks Toby

**Comment by tobyplowy** [comment]
@D00Med this is the guy who wants to do music

**Comment by SamLabbato** [comment]
so what kind of music do you need for what purposes?

**Comment by tobyplowy** [comment]
@D00Med this is on you what do we need

**Comment by SamLabbato** [comment]
xD ok

**Comment by D00Med** [comment]
Great. Have you done music or sounds for mods before? (just so I can have a look as an example).
Just background music would be good, like the ambience mod(if you know of it)

**Comment by SamLabbato** [comment]
no

**Comment by D00Med** [comment]
Ok then

**Comment by tobyplowy** [comment]
@D00Med @SamLabbato I will be offline for 10 min brb

**Comment by SamLabbato** [comment]
but i do have a plethora of instruments and know how to play them well. I'd be very willing to give it a shot

**Comment by D00Med** [comment]
Ok, that's good. I just have to check, have you ever played a legend of zelda game?

**Comment by SamLabbato** [comment]
yeah

**Comment by SamLabbato** [comment]
i know how to play a couple of their songs, but I'll be sure to do my research anyway

**Comment by D00Med** [comment]
Ok, so you know what the music is like. 
I'm not too sure about exactly what music I want in the subgame, so feel free to come up with something just for playing when nothing in particular is happenning, or maybe for when the bosses have spawned

**Comment by SamLabbato** [comment]
ok, i was just hoping for a general guideline of like, "oh we need a song here and it needs sound kind of sad/energetic/upbeat/etc"

**Comment by D00Med** [comment]
Ok, energetic music would be good for starters I think.
 I'll have to ask Toby

**Comment by SamLabbato** [comment]
ok. you said there were bosses. what kind of bosses? and where would they spawn?

**Comment by D00Med** [comment]
There are a few; Ganon, Volvagia, king dodongo. 
They spawn when a certain block is placed.
I can sort out triggers for the music.

**Comment by tobyplowy** [comment]
@D00Med @SamLabbato hey I'm back

**Comment by SamLabbato** [comment]
welcome. I think noah was asking if he could post on here or something :/

**Comment by SamLabbato** [comment]
btw D00Med, does any scenery spawn in with them or just the mob itself?

**Comment by D00Med** [comment]
Just the mob itself

**Comment by SamLabbato** [comment]
ok, I was just wondering...atmosphere plays a big role in making the music.

**Comment by D00Med** [comment]
I'm hoping to eventually make dungeons to spawn with them.

**Comment by SamLabbato** [comment]
ok. that helps a lot

**Comment by tobyplowy** [comment]
@D00Med I'm doing some research on music at the moment

**Comment by D00Med** [comment]
Ok

**Comment by WinkingBaby** [comment]
Will you be using the Minetest ambience mod as a base for the music?

**Comment by D00Med** [comment]
Hello. I think so, it should be easier than trying to do it myself

**Comment by tobyplowy** [comment]
@D00Med @SamLabbato I think the Boss Battle music sound Something like this https://m.youtube.com/watch?list=PL3FFF8C9078F1F58C&params=OAFIAVgC&v=bsAPO2UQtYA&mode=NORMAL

**Comment by tobyplowy** [comment]
@SamLabbato I Would recommend listening to the full album for inspiration https://m.youtube.com/watch?list=PL3FFF8C9078F1F58C&params=OAFIAVgC&v=bsAPO2UQtYA&mode=NORMAL

Or at least the first couple songs

**Comment by WinkingBaby** [comment]
Will you be adding additional sounds to the ambience mod, or would you just be replacing the sound files that are already there?

**Comment by D00Med** [comment]
replacing and removing some sounds. I'll probably use one of the modified versions with less sounds

**Comment by WinkingBaby** [comment]
I think a hyrule field sounding song would fit nice for just walking around the world.

**Comment by D00Med** [comment]
yeah that would be good

**Comment by tobyplowy** [comment]
Im gone for a bit

**Comment by D00Med** [comment]
ok

**Comment by D00Med** [comment]
Be back in a while

**Comment by D00Med** [comment]
I'm back

**Comment by WinkingBaby** [comment]
How would you feel about a piano sound playing whenever you attack a boss? Kind of like attacking people in loz wind waker.

**Comment by D00Med** [comment]
I've never played wind waker, so I don't really know what you are talking about

**Comment by WinkingBaby** [comment]
https://youtu.be/sFi8NB2PTw4?t=22m33s
Check out this link. When he fights it has a little musical effect. Could be a cool thing to add in.

**Comment by D00Med** [comment]
What about this? https://youtu.be/67Z5VKTwAls?t=223

**Comment by tobyplowy** [comment]
@D00Med I like both! I can't decide :/

**Comment by SamLabbato** [comment]
I just made a song on the fly. might need to be refined to your liking, but i like how it sounds now. it's kind of sounds like it'd be good for a forest theme or something, but if you don't need it i can scrap it...still working on the boss themes...they're going to be hard :/

**Comment by tobyplowy** [comment]
@SamLabbato that's great but where is the song?  I would love to hear it

**Comment by D00Med** [comment]
same

**Comment by tobyplowy** [comment]
@D00Med I will be able to do some work today

**Comment by D00Med** [comment]
Ok, great.
There were models I was hoping you could make.
Could you please make models for these?
http://individual.utoronto.ca/roninkengo/pictures/bluedarknut.jpg
http://vignette3.wikia.nocookie.net/zelda/images/b/b8/Armos_Artwork_(Ocarina_of_Time).png/revision/latest?cb=20100411224612

**Comment by tobyplowy** [comment]
@D00Med yes I will try

**Comment by D00Med** [comment]
Thanks.

**Comment by tobyplowy** [comment]
@D00Med I will first take a look at the latest unstable

**Comment by SamLabbato** [comment]
oh lol sorry, i didn't see your comments...if you call me, i can play it for you

**Comment by tobyplowy** [comment]
@SamLabbato but how will d00med hear it?

**Comment by SamLabbato** [comment]
hm.......i don't know..... i could try recording it onto sound cloud, but the audio quality will be bad... :/ but i guess it'll be bad on skype as well.
