### ISSUE TITLE
Broken Fence Recipe

### ISSUE THREAD

**Issue by ClaudiusMinimus** [D00Med/LegendofMinetest#21]
The recipe for specific wood fences is broken on line 30 of: .minetest/games/LegendofMinetest/mods/default/nodes/fences.lua. 

The fix is shown below, though you will want to clean it up.

```
	minetest.register_craft({
		output = itemstring .. ' 4',
		recipe = {
--			{'group:stick', def.material, 'group:stick'},
--			{'group:stick', def.material, 'group:stick'},
			{def.material, 'group:stick', def.material},
			{def.material, 'group:stick', def.material},
		}
	})
end
```

**Comment by D00Med** [comment]
How are the current recipes broken? they work fine for me

**Comment by ClaudiusMinimus** [comment]
When I just your recipe, it conflicts with the gate recipe and there is no alternate, so it shows your fence recipe, but the output is a wood gate. The recipe I am showing is the standard one used.

**Comment by D00Med** [comment]
What version are you using? it's working fine for me.

**Comment by ClaudiusMinimus** [comment]
I am pulling from your git repo and I updated before I submitted this issue report.
Regarding MT: I use the flatpak release 0.4.15 and I also have the dev ppa for the daily build.

BTW: I am having a blast playing your sub-game! :+1:

**Comment by D00Med** [comment]
Ok, I'll have another look anyway.
That's great

**Comment by mckaygerhard** [comment]
@ClaudiusMinimus  the pull #39 was merge.. this issue  was deprecated cos now the recipe is moved and defined at default/functions.lua line [https://github.com/D00Med/LegendofMinetest/blob/cae7b83341ef44b2d9c85930d2b7e49396163952/mods/default/functions.lua#L256](https://github.com/D00Med/LegendofMinetest/blob/cae7b83341ef44b2d9c85930d2b7e49396163952/mods/default/functions.lua#L256)  and is corrrectly defined as you posted.

so must be close due deprecation and then to start to port to 5.0.1 and to start to be stable in 0.4.17, thanks in advance @D00Med  (lest remenber only port and stability for now)
