### ISSUE TITLE
Rain falls through slabs and slopes

### ISSUE THREAD

**Issue by ClaudiusMinimus** [D00Med/LegendofMinetest#22]
I created a house and used slopes and slabs on the roof. When it rains, the rain goes right through the slabs and slopes. I understand that both of these nodes are semi-transparent, but I have not experienced this issue before.

**Comment by mckaygerhard** [comment]
the pull #39 was merge.. this issue must be checked @ClaudiusMinimus }..  and if there's no response must be close to start to port to 5.0.1 and to start to be stable in 0.4.17, thanks in advance @D00Med  (lest remember only port and stability for now)

**Comment by mckaygerhard** [comment]
tested and it seems works and if you put in some way of course will be ..  closed plese @D00Med if there's no reply

![screenshot_20220128_112647](https://user-images.githubusercontent.com/1571724/151574196-cf4f8ef0-33ff-47e6-b4d2-b49d13f96618.png)

**Comment by mckaygerhard** [comment]
already fixed since pr #39 and this behaviour happened if slabs are thin or have holes
