### ISSUE TITLE
Flying caveplants in subrosian caves

### ISSUE THREAD

**Issue by verymilan** [D00Med/LegendofMinetest#23]
Hi, i just noticed a bunch of caveflowers placed in the air by the subrosian cave generation:

![screenshot_20170302_135644](https://cloud.githubusercontent.com/assets/10698140/23508257/1c556478-ff51-11e6-96a9-c3c414aa911e.png)

**Comment by D00Med** [comment]
It should be fixed now(I haven't actually tested yet). They won't spawn deeper than the start of subrosia/hell.
Thanks for pointing out the problem

**Comment by verymilan** [comment]
Seems like a valid workaround 👍

**Comment by verymilan** [comment]
Whups, there is still some stoneweed, hm?^^

**Comment by D00Med** [comment]
Thanks, should be right now
