### ISSUE TITLE
New update?

### ISSUE THREAD

**Issue by tobyplowy** [D00Med/LegendofMinetest#25]
@D00Med I think we should release a small update that fixes a couple of problems and adds a couple of features

Like particle glow
And maybe the climbing mechanic from breath of the wild

**Comment by D00Med** [comment]
@tobyplowy That's a good idea, in fact I've already started on it. 
I added some more foods(mostly for biomes without much food), and a boat yesterday, just haven't uploaded it yet.

**Comment by tobyplowy** [comment]
@D00Med and what do you think about the climbing mechanic from breath of the wildl

**Comment by D00Med** [comment]
@tobyplowy idk, how does it work?

**Comment by tobyplowy** [comment]
@D00Med If you climb you have a stamina sircle (its a bar but it's round XD)  that depletes slowly and if it depletes completely you fall (and probably die depending On were You Fall and on what you Fall)

Just Google The Legend of Zelda Breath Of The Wild climbing Mechanic and search for a video I'm sure you're going to find it :)

**Comment by D00Med** [comment]
@tobyplowy Ok then

**Comment by D00Med** [comment]
@tobyplowy I looked up a list of all the new items in botw, I don't know whether to be pleased or annoyed. 
So much work if I want to add them all xD

**Comment by tobyplowy** [comment]
@D00Med Lol yeh

**Comment by D00Med** [comment]
@tobyplowy only just now I found out that math.random() only works with whole numbers.
I've been using it with decimals for ages O.o

**Comment by tobyplowy** [comment]
@D00Med no Idea what that means but that must suck!

**Comment by D00Med** [comment]
@tobyplowy Yeah it does.

**Comment by tobyplowy** [comment]
@D00Med are you going to add all the crafting items from breath of the wild?

**Comment by tobyplowy** [comment]
@D00Med do you need help with textures for those?

**Comment by D00Med** [comment]
@tobyplowy I'll certainly add some of them. 
Hmm maybe. I don't think I'll work on that just yet anyway, I'd rather make more progress on farlands

**Comment by tobyplowy** [comment]
@D00Med ok :)

**Comment by mckaygerhard** [comment]
the pull #39 was merge.. this issue must be close to start to port to 5.0.1 and to start to be stable in 0.4.17, thanks in advance (lest remenber only port and stability for now)
