### ISSUE TITLE
I found a few bugs and problems

### ISSUE THREAD

**Issue by tobyplowy** [D00Med/LegendofMinetest#27]
First is cuccos they don't seem to spawn but normal chickens do (also normal chickens shuld be removed)

Octorok projectiles don't hurt the player

**Comment by D00Med** [comment]
@tobyplowy Were you wearing armour or a shield when you were attacked by the Octorock?

**Comment by D00Med** [comment]
![](http://www.belfasttelegraph.co.uk/news/uk/article30902655.ece/ALTERNATES/h342/police.jpg)

**Comment by tobyplowy** [comment]
@D00Med No I was watching a YouTube video You know that Guy that makes the legend of Minetest Let's Play vids he wears wooden armor i think

**Comment by D00Med** [comment]
@tobyplowy Ok. I think armour blocks their attack very easily, I think I'll raise the damage and see if that fixes it

**Comment by tobyplowy** [comment]
![stock-photo-confused-young-man-in-the-car-stopped-by-policeman-326490668](https://user-images.githubusercontent.com/16853304/29269174-76092498-80f0-11e7-935c-0d73072eaf22.jpg)

**Comment by tobyplowy** [comment]
@D00Med Ok

**Comment by D00Med** [comment]
@tobyplowy offtopic: I finished the firework changes. 
Also it's late here, so I'm going now.

**Comment by tobyplowy** [comment]
@D00Med Ok good and see you later
