### ISSUE TITLE
Game crashes when using saddle

### ISSUE THREAD

**Issue by dyskos** [D00Med/LegendofMinetest#30]
Hi, I've been playing your subgame with my girlfriend, and noticed that there were horses (presumably from kpgmobs?), and when I tried to put a saddle on one, it crashed the game. I noticed that there were actually two different saddles, though they looked the same. Maybe they just have different IDs? Well the first one "works" (at least until using it crashes the game), but the other one does nothing.

Also, the yellow ocarina that should spawn a horse says the entity is not defined.

![image](https://user-images.githubusercontent.com/22121493/34457071-19835f54-ed5b-11e7-8f94-d044cd9f8159.png)

![image](https://user-images.githubusercontent.com/22121493/34457081-3c17a282-ed5b-11e7-9ce8-aadbd6e8a4d2.png)

**Comment by D00Med** [comment]
Should be fixed now, there is only one kind of saddle, the ocarina should work, and I updated the horse to use the new vehicles functions (so no more crashing hopefully).
