### ISSUE TITLE
Server sent wrong hud hotbar image (sent value: 'gui_hotbar.png')

### ISSUE THREAD

**Issue by jcfrosty** [D00Med/LegendofMinetest#38]
Server sent wrong hud hotbar image (sent value: 'gui_hotbar.png')
Server sent wrong hud hotbar selected image (sent value: 'gui_hotbar_selected
![20180627_190750](https://user-images.githubusercontent.com/13701401/42058102-f055c42e-7ae4-11e8-89af-55984b1aadfa.jpg)
.png')

**Comment by D00Med** [comment]
idk why this happens in 0.4.17, it's very odd. But it's fixed in the update branch, which will hopefully be merged soon.

**Comment by mckaygerhard** [comment]
fixed since PR #39  was merged, so closing this.. please only open a new pull request or reopen this with justifications and patches

![screenshot_20220202_100331](https://user-images.githubusercontent.com/1571724/152168732-8982e4e5-0d68-49d1-845f-a674fd915091.png)
