### ISSUE TITLE
Other suggestions or improvements

### ISSUE THREAD

**Issue by D00Med** [D00Med/LegendofMinetest#4]

**Comment by D00Med** [comment]
@tobyplowy Should I remove the hell mod?
It didn't work out too well I think. Now that I've got placing schematics worked out it could be a lot better though. I could add dungeons and villages. Oh and for some reason the subrosians don't seem to spawn.

**Comment by tobyplowy** [comment]
@D00Med yeh mayby

**Comment by D00Med** [comment]
should I add the ice biome back into legend of minetest?

**Comment by tobyplowy** [comment]
@D00Med yes

**Comment by D00Med** [comment]
ok, I will also add some structures to it, so that it is more interesting

**Comment by D00Med** [comment]
I have added the ice biome again, and also a swamp biome.
The swamp biome is very WIP, but it will hopefully look good when I am done.
Also I fixed the problem with the conifer biome.

**Comment by WinkingBaby** [comment]
Does Ganon have a dungeon made for him to spawn in?

**Comment by D00Med** [comment]
Not yet, I will make one though.

**Comment by WinkingBaby** [comment]
Just wanted to let you know. In certain situations you can see through walls with the third person view.

**Comment by D00Med** [comment]
Oh, that's a bit odd, but doesn't that sometimes happen in the default game?
I've done it before I think.

**Comment by D00Med** [comment]
I've been adding buildings and villages to the game, but it's slow going and I'm not great at building stuff.
So, if you guys want to help, that'd be really great.
Otherwise I'm thinking of asking on the forums for people to make some buildings or dungeons.

**Comment by D00Med** [comment]
@tobyplowy I'm thinking of improving the hookshot so that players can swing on it, would you be interested in this?(I was thinking it could be used for minetestia too)

**Comment by tobyplowy** [comment]
@D00Med Let Me Guess you got this from https://www.reddit.com/r/Minetest/comments/5ovz7w/if_someone_was_to_make_a_super_awesome_subgame/

**Comment by tobyplowy** [comment]
@D00Med I'm not sure If this Would Be useful I just want to point at something and fly at it but if it's implemented in a good way then yes I guess

**Comment by tobyplowy** [comment]
@D00Med also are you going to work on the weapingwillow trees today?

**Comment by D00Med** [comment]
I was already considering it, but seeing that made it more important ;)

> I just want to point at something and fly at it but if it's implemented in a good way then yes I guess

Yeah I can at least do that(I just need another entity after the hook)
Yes I will work on the weeping willows

**Comment by tobyplowy** [comment]
@D00Med Have You seen My latest comment on https://github.com/D00Med/minetestia/issues/1 it's going to be very useful in the future

**Comment by D00Med** [comment]
I will have a look

**Comment by tobyplowy** [comment]
@D00Med can you add the thing that makes it so the torch gives light if you hold it

Like you did in farlands a copple days ago

**Comment by tobyplowy** [comment]
@D00Med the guy that does the letsplay vids that asked it https://youtu.be/L6n0oHibVWU

**Comment by D00Med** [comment]
@tobyplowy Already done

**Comment by D00Med** [comment]
;)

**Comment by tobyplowy** [comment]
@D00Med ( ͡° ͜ʖ ͡°)
